# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - python --version ; pip --version  # For debugging
  - pip install pdm
  - pdm install
  - source .venv/bin/activate

# test:
#   tags:
#     - dockerbased
#   script:
#     - make test

run:
  tags:
    - dockerbased
  script:
    - make build
  artifacts:
    paths:
      - dist/*

pages:
  tags:
    - dockerbased
  script:
    - make docs-test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  tags:
    - dockerbased
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
