--- !MinioConfig

name: local-test
endpoint: 127.0.0.1:9000
access_key: minioadmin
secret_key: minioadmin
secure: False
config: tests/resources/local-test.yaml
secret_backend:
  type: keepass
  config:
    kdbx: secrets.kdbx
    generate_missing: True
