minio:
  - name: cluster1
    endpoint: s3.example.org
    access_key: abc123
    secret_key: abcdefgh12345678
    secure: True
  - name: cluster2
    endpoint: s3.example.net
    keepass:
      kdbx: /path/to/file.kdbx
      path: root/s3/cluster2
