site_name: MinIO Manager
repo_url: https://github.com/alveel/minio-manager
site_url: https://alveel.github.io/minio-manager
site_description: Declare what MinIO buckets, IAM policies, ILM policies you want, and let MinIO Manager do the work.
site_author: Alwyn Kik
site_dir: public
edit_uri: edit/main/docs/
repo_name: alveel/minio-manager
copyright: Maintained by <a href="https://github.com/alveel">Alwyn Kik</a>.

nav:
  - Home: index.md
  - MinIO Resources: resources.md
  - Setup: setup.md
  - Configuration: configuration.md
  - Modules: modules.md
plugins:
  - search
  - autorefs
  - mkdocstrings: {}
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alveel/minio-manager
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/minio-manager

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
  - pymdownx.snippets:
      base_path: ['.']
      check_paths: true
  - pymdownx.superfences:
